server:
  port: 8080 # พอร์ตหน้าด่านที่เปิดรับแขก (React จะยิงมาที่พอร์ตนี้พอร์ตเดียว)

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      # อนุญาตให้หน้าบ้าน React (พอร์ต 5173) ยิง API เข้ามาได้โดยไม่ติด Error สีแดงๆ บน Browser
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173" 
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"

      # กฎการเลี้ยวรถ (Routing Rules)
      routes:
        # 1. กฎสำหรับ User Service
        - id: user-service
          uri: http://localhost:8081           # ปลายทางที่จะส่งไป
          predicates:
            - Path=/api/users/** # ถ้า URL เริ่มต้นด้วย /api/users/ ให้ส่งมาที่นี่

        # 2. กฎสำหรับ Product Service
        - id: product-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/products/**

        # 3. กฎสำหรับ Order Service
        - id: order-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/orders/**

        # 4. กฎสำหรับ Loyalty Service
        - id: loyalty-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/loyalty/**, /api/rewards/** # สามารถดักได้หลาย Path ใน Service เดียว

        # 5. กฎสำหรับ Report Service
        - id: report-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/reports/**